spring:
  application:
    name: Digital_Chief_Test_Task
  datasource:
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    password: ${POSTGRES_USER}
    username: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: create
server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: character
    key-store-type: PKCS12
    key-alias: mycert
